name: Build

on:
  push:
    branches:
      - 'master'
    paths:
      - src/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./src/node/addon/
            tag: gabisonfire/knightcrawler-addon:latest
          - context: ./src/node/addon-jackett/
            tag: gabisonfire/knightcrawler-addon-jackett:latest
          - context: ./src/node/consumer/
            tag: gabisonfire/knightcrawler-consumer:latest
          - context: ./src/producer/
            tag: gabisonfire/knightcrawler-producer:latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push ${{ matrix.tag }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ matrix.tag }}